package ar.strellis.com.bgpsec.event;

public enum BgpEvent 
{
	MANUAL_START(1),
	MANUAL_STOP(2),
	AUTOMATIC_START(3),
	MANUAL_START_PASSIVE_TCP_ESTABLISHMENT(4),
	AUTOMATIC_START_PASSIVE_TCP_ESTABLISHMENT(5),
	AUTOMATIC_START_DAMP_PEER_OSCILLATIONS(6),
	AUTOMATIC_START_DAMP_PEER_OSCILLATIONS_PASSIVE_TCP_ESTABLISHMENT(7),
	AUTOMATIC_STOP(8),
	CONNECT_RETRY_TIMER_EXPIRES(9),
	HOLD_TIMER_EXPIRES(10),
	KEEPALIVE_TIMER_EXPIRES(11),
	DELAY_OPEN_TIMER_EXPIRES(12),
	IDLE_HOLD_TIMER_EXPIRES(13),
	TCP_CONNECTION_VALID(14),
	TCP_CR_INVALID(15),
	TCP_CR_ACKED(16),
	TCP_CONNECTION_CONFIRMED(17),
	TCP_CONNECTION_FAILS(18),
	BGP_OPEN(19),
	BGP_OPEN_DELAY_OPEN_TIMER_RUNNING(20),
	BGP_HEADER_ERR(21),
	BGP_OPEN_MSG_ERR(22),
	OPEN_COLLISION_DUMP(23),
	NOTIF_MSG_VER_ERR(24),
	NOTIF_MSG(25),
	KEEP_ALIVE_MSG(26),
	UPDATE_MSG(27),
	UPDATE_MSG_ERR(28);
	
	private final int id;
	BgpEvent(int idNumber)
	{
		id=idNumber;
	}
	public int event_id()
	{
		return id;
	}
}
