/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ar_strellis_com_bgpsec_routingconfig_RoutingConfigurer */

#ifndef _Included_ar_strellis_com_bgpsec_routingconfig_RoutingConfigurer
#define _Included_ar_strellis_com_bgpsec_routingconfig_RoutingConfigurer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
