/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ar_strellis_com_bgpsec_routingconfig_RoutingConfigurerNml */

#ifndef _Included_ar_strellis_com_bgpsec_routingconfig_RoutingConfigurerNml
#define _Included_ar_strellis_com_bgpsec_routingconfig_RoutingConfigurerNml
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ar_strellis_com_bgpsec_routingconfig_RoutingConfigurerNml
 * Method:    add_network_via_nml
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ar_strellis_com_bgpsec_routingconfig_RoutingConfigurerNml_add_1network_1via_1nml
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     ar_strellis_com_bgpsec_routingconfig_RoutingConfigurerNml
 * Method:    list_interfaces_via_nml
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ar_strellis_com_bgpsec_routingconfig_RoutingConfigurerNml_list_1interfaces_1via_1nml
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
